authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"
urlpatterns = [
    path("login", views.LoginView.as_view(), name = "login"),
    path("register", views.RegisterView.as_view(), name = "register"),
    path("logOut", views.LogOutView.as_view(), name = "logOut")
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog_site.urls")),
    path("auth/", include("authentication.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

authentication/forms.py
from django import forms

class LoginForm(forms.Form):
    username_email = forms.CharField(max_length=200, required=True, label="Ingrese username o email: ",error_messages={
        'required': 'This field is required'
    })
    password = forms.CharField(max_length=200, widget=forms.PasswordInput, label="Contraseña: ",required=True, error_messages={
        'required': 'This field is required'
    })


class RegisterForm(forms.Form):
    name = forms.CharField(max_length=200, required=True)
    last_name = forms.CharField(max_length=200, required=True)
    username = forms.CharField(max_length=200, required=True)
    email = forms.EmailField(max_length=200, required=True)
    #include image field
    password = forms.CharField(max_length=200, required=True, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=200, required=True, widget=forms.PasswordInput)

authentication/views.py
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import FormView
from django.urls import reverse

from .forms import *
# Create your views here.

class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, "authentication/login.html", {
            "form":form
        })
    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username_email = form.cleaned_data['username_email']
            password = form.cleaned_data['password']
            if '@' in username_email:
                try:
                    #check if user in table
                    user_model = User.objects.get(email = username_email)
                    #authenticate
                    user = authenticate(request, username = user_model.username, password = password)
                    if user is not None:
                        login(request, user)
                        return redirect(reverse("blog_site:index"))
                    else:
                        return render(request, "authentication/login.html", {
                            "form": form,
                            "message": "Los datos no coinciden"
                        })
                except User.DoesNotExist:
                    return render(request, "authentication/login.html", {
                        "form": form,
                        "message": 'El correo ingresado es incorrecto'
                    })
            else:
                #if not email then username
                try:
                    #check if user in table
                    user_model = User.objects.get(username = username_email)
                    #authenticate
                    user = authenticate(request, username = user_model.username, password = password)
                    if user is not None:
                        login(request, user)
                        return redirect(reverse("blog_site:index"))
                    else:
                        return render(request, "authentication/login.html", {
                            "form": form,
                            "message": 'Los datos no coinciden'
                        })
                except User.DoesNotExist:
                    return render(request, "authentication/login.html", {
                        "form": form,
                        "message": 'El usuario ingresado es incorrecto'
                    })
                    
    
class LogOutView(View):
    def post(self, request):
        logout(request)
        return(redirect("blog_site:index"))

class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "authentication/register.html", {
            "form": form
        })
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.get(email = form.cleaned_data['email'])
            except User.DoesNotExist:
                if form.cleaned_data['password'] != form.cleaned_data['confirm_password']:
                    return render(request, "authentication/register.html", {
                        "form": form,
                        "message": 'Las contraseñas no coinciden'
                    })
                try: 
                    user = User.objects.create_user(first_name= form.cleaned_data['name'], last_name = form.cleaned_data['name'], username=form.cleaned_data['username'], email = form.cleaned_data['email'], password= form.cleaned_data['password'])
                    user.save()
                    login(request, user)
                    return redirect(reverse("blog_site:index"))
                except IntegrityError:
                    return render(request, "authentication/register.html", {
                        "form": form,
                        "message": 'Ya existe ese usuario'
                    })
            if user is not None:
                return render(request, "authentication/register.html", {
                    "form": form,
                    "message": 'El correo electronico ya esta vinculado con una cuenta existente'
                })
            
        else: 
            return render(request, "authentication/register.html", {
                "form": form
            })

authentication/templates/authentication/base_auth.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'authentication/style.css'%}">
    {% block estilo %}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock%}</title>
</head>
<body>
    <main>
        <section class="image-section">
            <img src="{% static 'authentication/megaphone.png'%}" id="megaphone">
            <img src="{% static 'authentication/blog3.png'%}" id="girl">
            <h4>Donde tus ideas cobran vida y tus palabras conectan con el mundo.</h4>
        </section>
        <section id="form">
            <div class="img">
                <img src="{% static 'authentication/blog-web.png'%}" alt="">
            </div>
            <h2>
                {% block frase %}
                {% endblock %}
            </h2>
            <h6>{% block redireccion%} {% endblock %}</h6>
            {% block form %}
            {% endblock %}
        </section>
    </main>
</body>
</html>

authentication/templates/authentication/login.html
{% extends 'authentication/base_auth.html' %}
{% block title %}
login
{% endblock %}
{% block frase %}
¡Bienvenido de vuelta!
{% endblock %}
{% block redireccion %}
¿No tienes cuenta? <a href="{% url 'auth:register'%}">Registrate</a>
{% endblock %}
{% block form %}
<form action="{% url 'auth:login'%}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <h3>{{field.label}}</h3>
    {{field}}
    {% if field.errors %}
    {% for err in field.errors%}
    <h4>{{err}}</h4>
    {% endfor %}
    {% endif %}
    {% endfor %}
    {% if message %}
    <h5>
        {{message}}
    </h5>
    {% endif %}
    <input type="submit" value="Sent">
</form>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'authentication/base_auth.html' %}
{% load static %}
{% block title %}
register
{% endblock %}
{% block estilo %}
<link rel="stylesheet" href="{% static 'authentication/register.css'%}">
{% endblock %}
{% block frase %}
¡Bienvenido!
{% endblock %}
{% block redireccion %}
¿Ya tienes cuenta? <a href="{% url 'auth:login'%}">Inicia sesión</a>
{% endblock %}
{% block form %}
<form action="{% url 'auth:register'%}" class="register" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        <h3>{{field.label}}</h3>
        {{field}}
        {% if field.errors %}
        {% for err in field.errors%}
        <h4>{{err}}</h4>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    {% if message %}
    <h3 class="message_h3">{{message}}</h3>
    {% endif %}
    <input type="submit" value="Sent">
</form>
{% endblock %}