authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"
urlpatterns = [
    path("login", views.LoginView.as_view(), name = "login"),
    path("register", views.RegisterView.as_view(), name = "register"),
    path("logOut", views.LogOutView.as_view(), name = "logOut")
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog_site.urls")),
    path("auth/", include("authentication.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

blog_site/urls.py
from django.urls import path

from . import views

app_name = "blog_site"
urlpatterns = [
    path("", views.index, name = "index"),
    path("posts", views.posts, name = "posts"),
    path("posts/<slug:slug>", views.DetailPostView.as_view(), name = "detail_post"),
    path("perfil", views.PerfilView.as_view(), name = "perfil"),
    path("Miperfil", views.MyProfileView.as_view(), name = "MiPerfil"),
    path("crear", views.CreateView.as_view(), name = "create_post"),
    path("borrar/<slug:slug>", views.BorrarView.as_view(), name = "borrar"),
    path("leer-despues/<int:id>/<slug:slug>", views.ReadLaterView.as_view(), name = "read_later"),
    path("user/<str:username>", views.UserProfileView.as_view(), name="user_profile"),
    path("search/", views.SearchView.as_view(), name="search")
]

blog_site/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.utils.text import slugify
import os


class Tag(models.Model):
    caption = models.CharField(max_length=20)
    def __str__(self):
        return f"{self.caption}"


class Post(models.Model):
    title = models.CharField(max_length=100)
    excerpt = models.CharField(max_length=600)
    image_name = models.ImageField(null=True, blank=True, upload_to="blog_images", default="blog_images/default_blog.png")
    date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)
    content = models.TextField(validators=[MinLengthValidator(10)])
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    tags = models.ManyToManyField(Tag, related_name="tags_post")
    def __str__(self):
        return f"{self.title}, created by {self.author}"
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

class UserProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name= "user")
    biografia = models.TextField(blank=True, null=True)
    profile_pic = models.ImageField(upload_to="profile_pictures", default="profile_pictures/default_profile.webp",blank=True, null=True)
    

blog_site/forms.py
from django import forms
from .models import *

# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfileModel
#         fields = '__all__'
#         exclude = ['user']
#         labels = {
#             "biografia": 'Ingrese una biografia: ',
#             "profile_pic": "Ingrese una foto de perfil: "
#         }
class ProfileForm(forms.Form):
    biografia = forms.CharField(widget=forms.Textarea, required=False, label="Ingrese una biografia: ")
    profile_pic = forms.ImageField(required=False, label="Ingrese una foto de perfil: ")

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'excerpt', 'image_name', 'content', 'tags']
        labels = {
            "title": 'Titulo del blog',
            "excerpt": 'Descripcion breve de lo que aborda el blog',
            "image_name": 'Imagen para el blog',
            "content": 'Contenido del blog',
            "tags": 'Tags'
        }

blog_site/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.views.generic.edit import FormView
from django.urls import reverse_lazy, reverse
from django.utils.safestring import mark_safe
from django.db.models import Q
from .models import *
from .forms import *
import markdown2
# Create your views here.
from datetime import date
import os

def index(request):
    profile_pic = None
    latest_posts = Post.objects.all().order_by("-date")[:2]
    if not request.user.is_authenticated:
        return render(request, "blog_site/index.html", {
        "posts": latest_posts,
        "profile_pic": profile_pic
    })
    try:
        profile_pic = UserProfileModel.objects.get(user = request.user)
    except UserProfileModel.DoesNotExist:
        profile_pic = None  
    return render(request, "blog_site/index.html", {
        "posts": latest_posts,
        "profile_pic": profile_pic
    })

@login_required(login_url="auth:index")
def get_date(post):
    return post['date']

@login_required(login_url="auth:index")
def posts(request):
    all_posts = Post.objects.all().order_by("-date")
    return render(request, "blog_site/all-posts.html", {
        "posts":all_posts, 
    })

class DetailPostView(LoginRequiredMixin,View):
    login_url = reverse_lazy("auth:login")
    def get(self, request, slug):
        detail_blog = Post.objects.get(slug = slug)
        blog_markdown = markdown2.markdown(detail_blog.content)
        blog_markdown = mark_safe(blog_markdown)
        return render(request, "blog_site/post-detail.html", {
            "detail_blog": detail_blog,
            "tags": detail_blog.tags.all(),
            "content": blog_markdown, 
        })

class UserProfileView(LoginRequiredMixin,View):
    login_url = reverse_lazy("auth:login")
    def get(self, request, username):
        user = User.objects.get(username = username)
        posts = user.posts.all()
        try:
            user_profile = UserProfileModel.objects.get(user = user)
            print(user_profile)
        except UserProfileModel.DoesNotExist:
            return render(request, "blog_site/userProfile.html", 
                          {
                              "posts": posts, 
                              "user": user,
                              "cantidad": len(posts)
                          })    
        return render(request, "blog_site/userProfile.html", {
            "posts": posts,
            "user_profile": user_profile, 
            "cantidad": len(posts)
        })

class MyProfileView(View):
    def get(self, request):
        user = User.objects.get(username = request.user)
        posts = user.posts.all()
        read_later = Post.objects.filter(id__in = request.session.get("save", []))
        try:
            userProfile = UserProfileModel.objects.get(user = request.user)
        except UserProfileModel.DoesNotExist:
            return render(request, "blog_site/miPerfil.html", {
            "userProfile": None,
            "guardados": len(request.session.get("save", [])),
            "posts": posts, 
            "read_later": read_later
        })
        return render(request, "blog_site/miPerfil.html", {
            "userProfile": userProfile,
            "guardados": len(request.session.get("save", [])),
            "posts": posts, 
            "read_later": read_later
        })
class ReadLaterView(LoginRequiredMixin,View):
    login_url = reverse_lazy("auth:login")
    def post(self, request, id, slug):
        #add to session
        if "save" not in request.session:
            request.session["save"] = []
        #borrar del leer mas tarde 
        if "save" in request.POST:
            if id in request.session["save"]:
                request.session["save"].remove(id)
        elif "not_save" in request.POST:
            if id not in request.session["save"]:
                request.session["save"].append(id)
        request.session.modified = True
        return redirect(reverse("blog_site:detail_post", kwargs={"slug": slug}))
        # if "save" not in request.session:
        #     request.session['save']

class PerfilView(LoginRequiredMixin, View):
    login_url = reverse_lazy("auth:login")
    def get(self, request):
        form = ProfileForm()
        try:
            perfil = UserProfileModel.objects.get(user = request.user)
        except UserProfileModel.DoesNotExist:
            return render(request, "blog_site/perfil.html", {
            "form": form
        })    
        return render(request, "blog_site/perfil.html", {
            "form": form,
            "perfil": perfil
        })
    
    def post(self, request):
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            #create new model instance
            #change both bio and profile pic
            if len(form.cleaned_data['biografia']) > 0 and form.cleaned_data['profile_pic'] is not None:
                profile = UserProfileModel(user = request.user, biografia = form.cleaned_data['biografia'], profile_pic = form.cleaned_data['profile_pic'])
                try:
                    profile.save()
                #unique constraint failling
                except IntegrityError:
                    user = request.user
                    userProfile = UserProfileModel.objects.get(user = user)
                    if userProfile.profile_pic:
                        userProfile.profile_pic.delete(save=False)
                        userProfile.save()
                    userProfile.profile_pic = form.cleaned_data['profile_pic']
                    userProfile.biografia = form.cleaned_data['biografia']
                    userProfile.save()
                return redirect(reverse("blog_site:perfil"))
            #just change bio
            elif len(form.cleaned_data['biografia']) > 0 and form.cleaned_data['profile_pic'] is None:
                print("b")
                try:
                    profile = UserProfileModel.objects.get(user = request.user)
                    profile.biografia = form.cleaned_data['biografia']
                    profile.save()
                except UserProfileModel.DoesNotExist:
                    profile = UserProfileModel(user = request.user, biografia = form.cleaned_data['biografia'])
                    profile.save()
                return redirect(reverse("blog_site:perfil"))
            #just change profile pic
            elif len(form.cleaned_data['biografia']) == 0 and form.cleaned_data['profile_pic'] is not None:
                print("c")
                profile = UserProfileModel.objects.get(user = request.user)
                try:
                    if profile.profile_pic:
                        profile.profile_pic.delete(save=False)
                        profile.save()
                    profile.profile_pic = form.cleaned_data['profile_pic']
                    profile.save()
                except UserProfileModel.DoesNotExist:
                    profile = UserProfileModel(user = request.user, profile = form.cleaned_data['profile_pic'])
                    profile.save()
                return redirect(reverse("blog_site:perfil"))
            return redirect(reverse("blog_site:perfil"))
        else:
            return render(request, "blog_site/perfil.html", {
            "form": form })

class CreateView(LoginRequiredMixin,View):
    login_url = reverse_lazy("auth:login")
    def get(self, request):
        form = PostForm()
        return render(request, "blog_site/create.html", {
            "form": form
        })
    def post(self, request):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            print(form.cleaned_data['title'])
            try:
                new_post.save()
                for tag in form.cleaned_data['tags']:
                    new_post.tags.add(tag)
            except IntegrityError:
                return render(request, "blog_site/create.html", {
                "form":form,
                "message": 'No pueden existir dos blogs con el mismo nombre'
            })
            #despues va a renderizar al post detallado
            return redirect(reverse("blog_site:index"))
        else:
            return render(request, "blog_site/create.html", {
                "form":form
            })
    
class BorrarView(View):
    def post(self, request, slug):
        blog = Post.objects.get(slug = slug)
        blog.delete()
        return redirect(reverse("blog_site:index"))
    
class SearchView(View):
    def post(self, request):
        search = request.POST['post']
        busqueda = Post.objects.filter(Q(title__icontains = search) | Q(author__username__icontains = search ) | Q(tags__caption__icontains = search )).distinct()
        print(busqueda)
        return render(request, "blog_site/search.html", {
            "search":search,
            "busquedas": busqueda,
            "cantidad": len(busqueda)
        })

blog_site/templates/blog_site/all-posts.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'blog_site/posts.css'%}">
{% endblock %}
{%block title %}
All posts
{% endblock%}

{%block body %}
<section id="all-posts">
    <h2>Todos los posts</h2>
    <ul>
        {% for post in posts %}
        {% include 'blog_site/includes/post.html'%}
        {% endfor %}
    </ul>
</section>
{% endblock %}

blog_site/templates/blog_site/create.html
{% extends 'base.html'%}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'blog_site/create.css'%}">
{% endblock %}
{% block title %}
Crear post
{% endblock %}
{% block body %}
<h2>Crear Post</h2>
<p> El contenido del blog debe estar escrito usando markdown, si no sabes usarlo acá te dejamos <a href="https://www.markdownguide.org/cheat-sheet/">una guia.</a></p>
<form action="{% url 'blog_site:create_post'%}" method="post" class="blog-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    {% if message %}
    <h4>{{message}}</h4>
    {% endif %}
    <input type="submit" value="Subir blog">
</form>
{% endblock %}

blog_site/templates/blog_site/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'blog_site/index.css'%}">
{% endblock %}

{% block title %}
My blog
{% endblock %}

{% block body %}
<section id="welcome">
    <header>
        {% if user.is_authenticated and profile_pic%}
        <img src="{{profile_pic.profile_pic.url}}" alt="foto del hermoso usuario uwus">
        <h2>{{user}}'s 
        <br>    
        blog</h2>
        {% elif user.is_authenticated and profile_pic is None %}
        <h6>
            Agrega una foto de perfil para que otros usuarios te reconozcan👀
            <br>
            <a href="" id="perfil">Agregar foto de perfil</a>
        </h6>
        <h2>{{user}}'s blog
        <br>  
        {% else %}
        <img src="{% static 'blog_site/yo2.jpeg'%}" alt="elo">
        <h2>Elo's 
        <br>    
        blog</h2>
        {% endif %}
    </header>
    {% if user.is_authenticated %}
    <p>Hola {{user}}, ¡es tu momento de demostrar tus habilidades como bloguero! Explora de diversos temas o crea blogs interesantes que otros podran leer.</p>
    {% else %}
    <p>Hola me llamo Elo 👻, este es mi blog para hablar de temas que me interesan, tu también puedes subir blogs de cosas que te interesan. <br> <a href="{% url 'auth:login'%}">¡Inicia sesión para empezar!</a></p>
    {% endif %}
</section>
<section id="latest-post">
    <div class="container">
        <h2>Lo último subido</h2>
        <div>
            {% for post in posts %}
            {% include 'blog_site/includes/post.html'%}
            {% endfor %}
        </div>
    </div>
</section>
{% if not user.is_authenticated %}
<section id="about">
    <div class="info">
        <h2>Un poco de información sobre mi 🤠</h2>
        <p>Soy estudiante de la carrera de ingeniería en computación en UNI Nicaragua.</p>
        <p>Empecé a programar en 2021 cuando entre al curso de <a href="https://code-fu.net.ni/">CS50x.ni</a> y desde ese entonces ha sido una de mis mayores pasiones. También he tenido el privilegio de impartir clases en el mismo curso que me enseño la pasión a programar ♥️</p>
        <p>Cada día intentando ser un poquito mejor que ayer, si me ven en la uni regalenme un cafecito.</p>
    </div>
    <div class="pics">
        <img src="{% static 'blog_site/yo3.jpeg'%}" alt="">
        <img src="{% static 'blog_site/cs50.jpeg'%}" id="cs50">
    </div>
</section>
{% endif %}
{% endblock %}

blog_site/templates/blog_site/miPerfil.html
{% extends 'base.html'%}
{% load static %}
{% block title %}
Mi perfil
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'blog_site/miperfil.css'%}">
{% endblock %}
{% block body %}
<h2>Mi perfil</h2>
<main>
    <section>
        <div class="profile">
            {% if userProfile %}
            <img src="{{userProfile.profile_pic.url}}" alt="">
            <p>{{userProfile.biografia}}</p>
            {% else %}
            <img src="{% static 'blog_site/default_profile.webp'%}" alt="">
            <p>No has escrito una biografia todavia.</p>
            {% endif %}
        </div>
        <div class="content">
            <h3>Tienes <b>{{guardados}}</b> blogs guardados para leer más tarde.</h3>
            <div class="posts read_later">
                {% for post in read_later %}
                {% include "blog_site/includes/post.html"%}
                {% empty %}
                <div class="no-post">
                    <h4>No has guardado ningún post todavia 😴</h4>
                    <img src="{% static 'blog_site/snoopy.gif'%}" alt="">
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <hr>
    <section id="mis-posts">
        <h3>Mis Posts</h3>
        <div class="posts">
            {% for post in posts %}
            {% include "blog_site/includes/post.html"%}
            {% empty %}
            <h3>Todavia no has escrito un blog ☹️.</h3>
            <h3>Empieza <a href="{% url 'blog_site:create_post'%}">tu primer blog</a> 😁</h3>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}

blog_site/templates/blog_site/perfil.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
perfil 
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'blog_site/perfil.css'%}">
{% endblock %}
{% block body %}
<h2>Configuraciones del perfil</h2>
<main>
    <section id="profile_form">
        <form action="{% url 'blog_site:perfil'%}" id="perfil" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for fields in form %}
            <h4>
                {{fields.label}}
            </h4>
            {{fields}}
            {% if fields.errors %}
            {% for err in fields.errors %}
            <h6>
                {{err}}
            </h6>
            {% endfor %}
            {% endif %}
            {% endfor %}
            <input type="submit" value="Actualizar perfil">
        </form>
    </section>
    <section id="profile_now">
        {% if perfil.profile_pic %}
        <img src="{{perfil.profile_pic.url}}" alt="">
        <p>
            {{perfil.biografia}}
        </p>
        {% else %}
        <img src="{% static 'blog_site/default_profile.webp'%}" alt="">
        {% if perfil.biografia %}
        <p> {{perfil.biografia}}</p>
        {% else %}
        <p>
            Escribe una biografia para que otros sepan de ti 😼
        </p>
        {% endif %}
        {% endif %}
    </section>
</main>
{% endblock %}

blog_site/templates/blog_site/post-detail.html
{% extends 'base.html'%}
{% load static %}
{% block title %}
Detalle post
{% endblock %}
{%block style %}
<link rel="stylesheet" href="{% static 'blog_site/post-detail.css'%}">
{% endblock %}
{% block body %}
<section id="summary">
    <article>
    <div>
        <h2>{{detail_blog.title}}</h2>
        <h5>Etiquetas: 
            {% for tag in tags %}
            <span>{{tag}}</span>
            {% endfor %}
        </h5>
        <form action="{% url 'blog_site:read_later' detail_blog.id detail_blog.slug%}" id="read-later" method="post">
            {% csrf_token %}
            <div>
                {% if detail_blog.id in request.session.save %}
                <label>Eliminar post del leer más tarde</label>
                <input type="image" src="{% static 'blog_site/save1.png'%}" id="save">
                <input type="hidden" name="save" value="save">
                {% else %}
                <label>Agregar post al leer más tarde</label>
                <input type="image" src="{% static 'blog_site/save2.png'%}" id="not_save">
                <input type="hidden" name="not_save" value="not_save">
                {% endif %}
            </div>
        </form>
    </div>
    <div class="address">
        <img src="{{detail_blog.image_name.url}}" alt="">
        <address id="author">Escrito por: <a href="{% url 'blog_site:user_profile' detail_blog.author%}"><b>{{detail_blog.author}}</b></a></address>
        <address>
            Actualizado el <b><time>{{detail_blog.date.date}}</time></b>
        </address>
    </div>
</article>
<main>
    {{content}}
</main>
{% if request.user == detail_blog.author %}
<form action="{% url 'blog_site:borrar' detail_blog.slug%}" id="borrar" method="post">
    {% csrf_token %}
    <input type="submit" value="Borrar Post">
</form>
{% endif %}
</section>
{% endblock %}

blog_site/templates/blog_site/search.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'blog_site/search.css'%}">
{% endblock %}
{% block title %}
Busqueda
{% endblock %}

{% block body %}
<h2>Se encontraron <span>{{cantidad}}</span> búsquedas similares a {{search}}</h2>
<main>
    <section>
        {% for post in busquedas %}
        <div>
            {% include "blog_site/includes/post.html"%}
        </div>
        {% empty %}
        <h3>No hay coincidencias con {{search}}</h3>
        {% endfor %}
    </section>
</main>
{% endblock %}

blog_site/templates/blog_site/userProfile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Perfil de usuario
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'blog_site/userProfile.css'%}">
{% endblock %}
{% block body %}
{% if not user_profile %}
<h2>Perfil de {{user}}</h2>
{%else%}
<h2>Perfil de {{user_profile.user}}</h2>
{% endif %}
<main>
    <section>
        {% if not user_profile %}
        <img src="{% static 'blog_site/default_profile.webp'%}">
        {% else %}
        <img src="{{user_profile.profile_pic.url}}">
        <p>{{user_profile.biografia}}</p>
        {% endif %}
        {% if cantidad != 0 %}
        <h4>{{user_profile.user}} ha subido {{cantidad}} posts 😎</h4>
        {% else %}
        <h4>{{user_profile.user}} ha subido {{cantidad}} posts 😴</h4>
        {% endif %}
        <img src="{% static 'blog_site/winnie.gif'%}">
    </section>
    <hr>
    <section class="user-posts">
        {% if not user_profile %}
        <h2>
            {{user}}'s posts
        </h2>
        {% else %}
        <h2>
            {{user_profile.user}}'s posts
        </h2>
        {% endif%}
        <div>
            {% for post in posts %}
            {% include 'blog_site/includes/post.html'%}
            {% empty %}
            <h4>{{user_profile.user}} no ha subido ningun post todavia.</h4>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}