authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"
urlpatterns = [
    path("login", views.LoginView.as_view(), name = "login"),
    path("register", views.RegisterView.as_view(), name = "register"),
    path("logOut", views.LogOutView.as_view(), name = "logOut")
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog_site.urls")),
    path("auth/", include("authentication.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

blog_site/urls.py
from django.urls import path

from . import views

app_name = "blog_site"
urlpatterns = [
    path("", views.index, name = "index"),
    path("posts", views.posts, name = "posts"),
    path("posts/<slug:slug>", views.DetailPostView.as_view(), name = "detail_post"),
    path("perfil", views.PerfilView.as_view(), name = "perfil"),
    path("Miperfil", views.MyProfileView.as_view(), name = "MiPerfil"),
    path("crear", views.CreateView.as_view(), name = "create_post"),
    path("borrar/<slug:slug>", views.BorrarView.as_view(), name = "borrar"),
    path("leer-despues/<int:id>/<slug:slug>", views.ReadLaterView.as_view(), name = "read_later"),
    path("user/<str:username>", views.UserProfileView.as_view(), name="user_profile"),
    path("search/", views.SearchView.as_view(), name="search")
]

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block style %}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <header id="main-navigation">
        <nav>
            <h1>
                {% if user.is_authenticated %}
                <a href="{% url 'blog_site:index'%}">{{user}}'s blog</a>
                {% else %}
                <a href="{% url 'blog_site:index'%}">Elo's blog</a>
                {% endif %}
            </h1>
            {% if user.is_authenticated %}
            <section class="section_anchors">
                <img src="{% static 'menu.png'%}" id="menu">
                <div class="anchors show_anchors" id="anchors">
                    <a href="{% url 'blog_site:posts'%}">Todos los Posts</a>
                    <a href="{% url 'blog_site:MiPerfil'%}">Mi perfil</a>
                    <a href="{% url 'blog_site:perfil'%}"> Configuraciones del perfil</a>
                </div>
            </section>
            <a href="{% url 'blog_site:create_post'%}" id="create">Crear Post</a>
            <form action="{% url 'auth:logOut'%}" method="post">
                {% csrf_token%}
                <button type="submit" id="logOut">Cerrar sesión</button>
            </form>
            {% else %}
            <a href="{% url 'auth:login'%}" id="a_login">Inicia sesión para ver todos los Posts</a>
            {% endif %}
        </nav>
        {% if user.is_authenticated %}
        <form action="{% url 'blog_site:search'%}" method="post">
            {% csrf_token %}
            <input type="text" name="post" placeholder="un post por etiqueta, autor o nombre">
        </form>
        {% endif%}
    </header>
    {% block body %}
    {% endblock %}
    <script src="{%static 'script.js'%}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>